import { annotationsType } from "../Types/AnnotedLetter";

export const annotations: annotationsType = {
  digraph: { unicode: "\u200b", valid: "none", type: "none" },
  main_stress: {
    mark: "dash below",
    unicode: "\u0329",
    valid: "vowel",
    type: "vowel",
  },
  secondary_stress: {
    mark: "double dash below",
    unicode: "\u0348",
    valid: "vowel",
    type: "vowel",
  },
  simple_seperator: {
    mark: "up tack below",
    unicode: "\u031d",
    valid: "between",
    type: "none",
  },
  left_seperator: {
    mark: "left tack below",
    unicode: "\u0318",
    valid: "between",
    type: "none",
  },
  right_seperator: {
    mark: "up tack below",
    unicode: "\u0319",
    valid: "between",
    type: "none",
  },
  both_seperator: {
    mark: "plus below",
    unicode: "\u031f",
    valid: "between",
    type: "none",
  },
  schwa: {
    mark: "hook above",
    unicode: "\u0309",
    valid: "consonant",
    type: "none",
  },
  natural: {
    mark: "tilde above",
    unicode: "\u0303",
    doublecode: "\u0360",
    valid: "vowel",
    type: "vowel",
    ipa: true,
  },
  plain: {
    mark: "comma above",
    unicode: "\u0313",
    valid: "vowel",
    type: "vowel",
    ipa: true,
  },
  broad: {
    mark: "bar above",
    unicode: "\u0304",
    doublecode: "\u035e",
    valid: "vowel",
    type: "vowel",
    ipa: true,
  },
  clear: {
    mark: "up arrow above",
    unicode: "\u0302",
    doublecode: "1dcd",
    valid: "vowel",
    type: "vowel",
    ipa: true,
  },
  central: {
    mark: "two dots above",
    unicode: "\u0308",
    valid: "vowel",
    type: "vowel",
    ipa: true,
  },
  iotted: {
    mark: "one dots above",
    unicode: "\u0307",
    valid: "vowel",
    type: "vowel",
    ipa: true,
  },
  round: {
    mark: "ring above",
    unicode: "\u030a",
    valid: "vowel",
    type: "vowel",
    ipa: true,
  },
  opaque: {
    mark: "down arrow above",
    unicode: "\u030c",
    valid: "vowel",
    type: "vowel",
    ipa: true,
  },
  idiphthong: {
    mark: "left dash above",
    unicode: "\u0300",
    valid: "vowel",
    type: "vowel",
    ipa: true,
  },
  udiphthong: {
    mark: "right dash above",
    unicode: "\u0301",
    valid: "vowel",
    type: "vowel",
    ipa: true,
  },
  w_semiconsonant: {
    mark: "w below",
    unicode: "\u032b",
    valid: "any",
    type: "consonant",
    ipa: true,
  },
  y_semiconsonant: {
    mark: "inverted w below",
    unicode: "\u033c",
    valid: "any",
    type: "consonant",
    ipa: true,
  },
  common_change: {
    mark: "ring below",
    unicode: "\u0325",
    valid: "consonant",
    type: "consonant",
    ipa: true,
  },
  voiced: {
    mark: "up arrow below",
    unicode: "\u032c",
    valid: "consonant",
    type: "consonant",
    ipa: true,
  },
  voiceless: {
    mark: "down arrow below",
    unicode: "\u032d",
    valid: "consonant",
    type: "consonant",
    ipa: true,
  },
  soft_voiced: {
    mark: "up block below",
    unicode: "\u033a",
    valid: "consonant",
    type: "consonant",
    ipa: true,
  },
  soft_voiceless: {
    mark: "down block below",
    unicode: "\u033b",
    valid: "consonant",
    type: "consonant",
    ipa: true,
  },
  hard_voiced: {
    mark: "up block and line below",
    unicode: "\u033a\u0331",
    valid: "consonant",
    type: "consonant",
    ipa: true,
  },
  hard_voiceless: {
    mark: "down block and line below",
    unicode: "\u033b\u0331",
    valid: "consonant",
    type: "consonant",
    ipa: true,
  },
  silent: {
    mark: "cross below",
    unicode: "\u0353",
    valid: "letter",
    type: "none",
  },
};

export const annotationCode = {
  851: "silent",
  809: "main_stress",
  840: "secondary_stress",
  797: "simple_seperator",
  792: "left_seperator",
  793: "right_seperator",
  799: "both_seperator",
  777: "schwa",
  771: "natural",
  787: "plain",
  772: "broad",
  770: "clear",
  776: "central",
  775: "iotted",
  778: "round",
  780: "opaque",
  768: "idiphthong",
  769: "udiphthong",
  811: "w_semiconsonant",
  828: "y_semiconsonant",
  805: "common_change",
  812: "voiced",
  813: "voiceless",
  826: "soft_voiced",
  827: "soft_voiceless",
  817: {
    826: "hard_voiced",
    827: "hard_voiceless",
  },
  8203: "digraph",
};

// export const nonInsertAnnotation = [
//   "silent",
//   // "main_stress",   deal with stress later
//   // "secondary_stress",
//   "schwa",
//   "natural",
//   "plain",
//   "broad",
//   "clear",
//   "central",
//   "iotted",
//   "round",
//   "opaque",
//   "idiphthong",
//   "udiphthong",
//   "w_semiconsonant",
//   "y_semiconsonant",
//   "common_change",
//   "voiced",
//   "voiceless",
//   "soft_voiced",
//   "soft_voiceless",
//   "hard_voiced",
//   "hard_voiceless",
// ]

// export const insertAnnotation = [
//   "main_stress",
//   "secondary_stress",
//   "simple_seperator",
//   "left_seperator",
//   "right_seperator",
//   "both_seperator",
//   "w_semiconsonant",
//   "y_semiconsonant",
// ]
